FROM python:3-slim

ARG DJANGO_ROOT=/var/www/server
ENV TZ America/Sao_Paulo
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get -y update && apt-get install -y sqlite tzdata

WORKDIR $DJANGO_ROOT

COPY ./server/requirements.txt .

RUN pip install -r requirements.txt

COPY ./server ./

# Django Entrypoint
COPY docker-python.sh /usr/bin
RUN chmod +x /usr/bin/docker-python.sh
ENTRYPOINT [ "docker-python.sh" ]
