# Generated by Django 3.1.3 on 2020-11-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=21)),
                ('rating', models.FloatField(default=0.0)),
                ('distance', models.CharField(max_length=20)),
                ('delivery_time', models.CharField(max_length=20)),
                ('delivery_tax', models.FloatField(default=0.0)),
                ('category_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.categorybusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
